name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    # Instalar Poetry
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    
    # Instalar dependencias con Poetry
    - name: Install dependencies
      run: |
        poetry install --no-root
    
    # Lint con ruff
    - name: Lint with ruff
      run: |
        poetry run ruff check .
    
    - name: Debug structure
      run: |
        ls -la
        find . -name "*.py" | sort
    
    # Ejecutar tests con pytest
    - name: Test with pytest
      run: |
            poetry run pytest \
              --ignore=tests/test_database.py \
              --ignore=tests/test_fastapiHelper.py \
              --ignore=tests/test_EmailAlert.py \
              --ignore=tests/test_token.py \
              --ignore=tests/test_telegram.py